version: "2.1"
services:
  golang-code-server:
    image: cnwangfei/code-server:go1.22.5_coder4.91.1_20240802
    container_name: golang-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
    # sudo chown -R 1000:1000 config/ go/
      - ./config:/config
      - ./go:/go
    ports:
      - 8443:8443 # code-server
      - 8080:8080 # test
    restart: unless-stopped
